package homeoffice.usertestdata;



import homeoffice.properties.FrameworkConfig;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class UserTestData {
    public static final String LOGIN_PAGE_TITLE;
    public static final String PRODUCTS_PAGE_TITLE;
    public static final String CART_PAGE_TITLE;
    public static final String CHECKOUT_STEP_ONE_PAGE_TITLE;
    public static final String CHECKOUT_STEP_TWO_PAGE_TITLE;
    public static final String CHECKOUT_COMPLETE_PAGE_TITLE;
    public static final String LOGIN_PAGE_HEADING;
    public static final String PRODUCTS_PAGE_HEADING;
    public static final String CART_PAGE_HEADING;
    public static final String CHECKOUT_STEP_ONE_PAGE_HEADING;
    public static final String CHECKOUT_STEP_TWO_PAGE_HEADING;
    public static final String CHECKOUT_COMPLETE_PAGE_HEADING;
    public static final String LOGIN_PAGE_PATH;
    public static final String INVENTORY_PAGE_PATH;
    public static final String INVENTORY_ITEM_PAGE_PATH;
    public static final String CART_PAGE_PATH;
    public static final String CHECKOUT_COMPLETE_PAGE_PATH;
    public static final String CHECKOUT_STEP_ONE_PAGE_PATH;
    public static final String FIRSTNAME;
    public static final String LASTNAME;
    public static final String EMAIL;
    public static final String POSTAL_OR_ZIP_CODE;
    public static final String CHECKOUT_OVERVIEW_PAGE_PATH;
    public static final String LOGIN_PAGE_URL;
    public static final String INVENTORY_PAGE_URL;
    public static final String CART_PAGE_URL;
    public static final String CHECKOUT_STEP_ONE_PAGE_URL;
    public static final String CHECKOUT_STEP_TWO_PAGE_URL;
    public static final String CHECKOUT_COMPLETE_PAGE_URL;
    public static final String MENU_ITEM_LOGOUT;
    public static final String LOGIN_BUTTON;
    public static final String CONTINUE_BUTTON;
    public static final String BUTTON_LABEL_CANCEL;
    public static final String BUTTON_KEY_LOGIN;
    public static final String STANDARD_USERNAME;
    public static final String LOCKED_OUT_USERNAME;
    public static final String PROBLEM_USERNAME;
    public static final String PERFORMANCE_GLITCH_USERNAME;
    public static final String ERROR_USER;
    public static final String VISUAL_USERNAME;
    public static final String PASSWORD_FOR_ALL_USERS;
    public static final String PASSWORD;
    public static final String INVALID_USERNAME;
    public static final String INVALID_PASSWORD;
    public static final String LOGIN_ERROR_MESSAGE;
    public static final String ERR_LOCKED_OUT;
    public static final String ERR_WRONG_CREDENTIALS;
    public static final String ERR_USERNAME_REQUIRED;
    public static final String ERR_PASSWORD_REQUIRED;
    public static final String ERR_FIRST_NAME_REQUIRED;
    public static final String ERR_POSTAL_CODE_REQUIRED;
    public static final String ERR_LAST_NAME_REQUIRED;
    public static final String CHECKOUT_COMPLETE_MESSAGE;
    public static final String DEFAULT_PRODUCT_QUANTITY;
    public static final String DEFAULT_PRODUCT_PRICE;
    public static final String DEFAULT_ORDER_TOTAL;
    public static final String CURRENCY_SYMBOL;
    public static final String BUTTON_LABEL_LOGIN;
    public static final String SAUCE_LABS_BIKE_LIGHT_TITLE;
    public static final String SAUCE_LABS_BACKPACK_TITLE;
    public static final String SAUCE_LABS_BOLT_TSHIRT_TITLE;
    public static final String SAUCE_LABS_FLEECE_JACKET_TITLE;
    public static final String SAUCE_LABS_ONESIE_TITLE;
    public static final String TEST_ALLTHETHINGS_TSHIRT_RED_TITLE;
    public static final String LIGHTHOUSE_COMMAND_PROPERTY;
    public static final String LIGHTHOUSE_COMMAND_ENV;
    public static final String LIGHTHOUSE_REPORT_PATH;
    public static final String APPLICATIONS_DOWNLOAD_FILEPATH;
    public static final String APPLICATIONS_UPLOAD_FILEPATH;
    public static final String REPORTING_CSV_DOWNLOAD_FILEPATH;
    public static final String APPLICATIONS_DOWNLOAD_FILENAME = "-Application forms.pdf";
    public static final String ACCESSIBILITY_REPORT_FILENAME;
    public static final String BUTTON_LABEL_ADD_TO_CART;
    public static final String BUTTON_LABEL_REMOVE;
    public static final String BUTTON_LABEL_CONTINUE_SHOPPING;
    public static final String BUTTON_LABEL_FINISH;
    public static final String BUTTON_LABEL_BACK_HOME;
    public static final String BUTTON_LABEL_CHECKOUT;
    public static final String BUTTON_LABEL_CONTINUE;
    public static final String BUTTON_LABEL_LOGOUT;
    public static final String BUTTON_LABEL_OPEN_MENU;
    public static final String BUTTON_LABEL_CLOSE_MENU;
    public static final String BUTTON_LABEL_RESET_APP_STATE;
    public static final String BUTTON_LABEL_ALL_ITEMS;
    public static final String BUTTON_LABEL_ABOUT;
    public static final String BUTTON_LABEL_LOGOUT_LINK;
    public static final String BUTTON_LABEL_LINKEDIN;
    public static final String BUTTON_LABEL_FACEBOOK;
    public static final String BUTTON_LABEL_TWITTER;
    public static final String BUTTON_LABEL_CONTINUE_TO_CHECKOUT;
    public static final String BUTTON_LABEL_BACK_TO_PRODUCTS;
    public static final String BUTTON_LABEL_SHOPPING_CART;
    public static final String BUTTON_LABEL_REMOVE_ITEM;
    public static final String BUTTON_LABEL_ADD_ITEM;
    public static final String BUTTON_LABEL_BACK;
    public static final String SORT_OPTION_NAME_AZ;
    public static final String SORT_OPTION_NAME_ZA;
    public static final String SORT_OPTION_PRICE_LH;
    public static final String SORT_OPTION_PRICE_HL;
    public static final String LOCATOR_CART_ICON;
    public static final String LOCATOR_BURGER_MENU_BUTTON;
    public static final String EXCEL_LOGIN_FILE_NAME;
    public static final String EXCEL_LOGIN_SHEET_NAME;
    public static final String CHECKOUT_OVERVIEW_PAGE_HEADING;
    private static final Logger log = LoggerFactory.getLogger(UserTestData.class);
    private static final FrameworkConfig CONFIG = FrameworkConfig.getInstance();

    static {
        LOGIN_PAGE_TITLE = CONFIG.getString("login_page_title", "Swag Labs");
        PRODUCTS_PAGE_TITLE = CONFIG.getString("products_page_title", "Products");
        CART_PAGE_TITLE = CONFIG.getString("cart_page_title", "Your Cart");
        CHECKOUT_STEP_ONE_PAGE_TITLE = CONFIG.getString("checkout_step_one_page_title", "Checkout: Your Information");
        CHECKOUT_STEP_TWO_PAGE_TITLE = CONFIG.getString("checkout_step_two_page_title", "Checkout: Overview");
        CHECKOUT_COMPLETE_PAGE_TITLE = CONFIG.getString("checkout_complete_page_title", "Checkout: Complete!");
        LOGIN_PAGE_HEADING = CONFIG.getString("login_page_heading", "Swag Labs");
        PRODUCTS_PAGE_HEADING = CONFIG.getString("products_page_heading", "Products");
        CART_PAGE_HEADING = CONFIG.getString("cart_page_heading", "Your Cart");
        CHECKOUT_STEP_ONE_PAGE_HEADING = CONFIG.getString("checkout_step_one_page_heading", "Checkout: Your Information");
        CHECKOUT_STEP_TWO_PAGE_HEADING = CONFIG.getString("checkout_step_two_page_heading", "Checkout: Overview");
        CHECKOUT_COMPLETE_PAGE_HEADING = CONFIG.getString("checkout_complete_page_heading", "Checkout: Complete!");
        LOGIN_PAGE_PATH = CONFIG.getString("login_page_path", "/");
        INVENTORY_PAGE_PATH = CONFIG.getString("inventory_page_path");
        INVENTORY_ITEM_PAGE_PATH = CONFIG.getString("inventory_item_page_path");
        CART_PAGE_PATH = CONFIG.getString("cart_page_path", "/cart.html");
        CHECKOUT_COMPLETE_PAGE_PATH = CONFIG.getString("checkout_complete_page_path");
        CHECKOUT_STEP_ONE_PAGE_PATH = CONFIG.getString("checkout_step_one_page_path");
        FIRSTNAME = CONFIG.getString("checkout.first_name");
        LASTNAME = CONFIG.getString("checkout.last_name");
        EMAIL = CONFIG.getString("checkout.email");
        POSTAL_OR_ZIP_CODE = CONFIG.getString("checkout.postal_or_zip_code");
        CHECKOUT_OVERVIEW_PAGE_PATH = CONFIG.getString("checkout_overview_page_path", "checkout-step-two.html");
        LOGIN_PAGE_URL = CONFIG.getString("login_url");
        INVENTORY_PAGE_URL = CONFIG.getString("inventory_url");
        CART_PAGE_URL = CONFIG.getString("cart_url");
        CHECKOUT_STEP_ONE_PAGE_URL = CONFIG.getString("checkout_step_one_url");
        CHECKOUT_STEP_TWO_PAGE_URL = CONFIG.getString("checkout_step_two_url");
        CHECKOUT_COMPLETE_PAGE_URL = CONFIG.getString("checkout_complete_url");
        MENU_ITEM_LOGOUT = CONFIG.getString("menu_item_logout");
        LOGIN_BUTTON = CONFIG.getString("login_button", "Login");
        CONTINUE_BUTTON = CONFIG.getString("continue_button");
        BUTTON_LABEL_CANCEL = CONFIG.getString("cancel_button");
        BUTTON_KEY_LOGIN = CONFIG.getString("button_key_login");
        STANDARD_USERNAME = CONFIG.getString("standard_user", "standard_user");
        LOCKED_OUT_USERNAME = CONFIG.getString("locked_out_user", "locked_out_user");
        PROBLEM_USERNAME = CONFIG.getString("problem_user", "problem_user");
        PERFORMANCE_GLITCH_USERNAME = CONFIG.getString("performance_glitch_user", "performance_glitch_user");
        ERROR_USER = CONFIG.getString("error_user", "error_user");
        VISUAL_USERNAME = CONFIG.getString("visual_user", "visual_user");
        PASSWORD_FOR_ALL_USERS = CONFIG.getString("password_for_all_users");
        PASSWORD = CONFIG.getString("password", "secret_sauce");
        INVALID_USERNAME = CONFIG.getString("invalid_user", "invalid_user");
        INVALID_PASSWORD = CONFIG.getString("invalid_password", "invalid_password");
        LOGIN_ERROR_MESSAGE = CONFIG.getString("login_error_message", "Epic sadface: Username and password do not match any user in this service");
        ERR_LOCKED_OUT = CONFIG.getString("err.locked_out", "Epic sadface: Sorry, this user has been locked out.");
        ERR_WRONG_CREDENTIALS = CONFIG.getString("err.wrong_credentials", "Epic sadface: Username and password do not match any user in this service");
        ERR_USERNAME_REQUIRED = CONFIG.getString("err.username_required", "Epic sadface: Username is required");
        ERR_PASSWORD_REQUIRED = CONFIG.getString("err.password_required", "Epic sadface: Password is required");
        ERR_FIRST_NAME_REQUIRED = CONFIG.getString("err.first_name_required", "Error: First Name is required");
        ERR_POSTAL_CODE_REQUIRED = CONFIG.getString("err.postal_code_required", "Error: Postal Code is required");
        ERR_LAST_NAME_REQUIRED = CONFIG.getString("err.last_name_required", "Error: Last Name is required");
        CHECKOUT_COMPLETE_MESSAGE = CONFIG.getString("checkout_complete_message", "Thank you for your order!");
        DEFAULT_PRODUCT_QUANTITY = CONFIG.getString("default_product_quantity");
        DEFAULT_PRODUCT_PRICE = CONFIG.getString("default_product_price");
        DEFAULT_ORDER_TOTAL = CONFIG.getString("default_order_total");
        CURRENCY_SYMBOL = CONFIG.getString("currency_symbol", "$");
        BUTTON_LABEL_LOGIN = CONFIG.getString("button_label_login", "Login");
        SAUCE_LABS_BIKE_LIGHT_TITLE = CONFIG.getString("sauce_labs_bike_light_title", "Sauce Labs Bike Light");
        SAUCE_LABS_BACKPACK_TITLE = CONFIG.getString("sauce_labs_backpack_title", "Sauce Labs Backpack");
        SAUCE_LABS_BOLT_TSHIRT_TITLE = CONFIG.getString("sauce_labs_bolt_tshirt_title", "Sauce Labs Bolt T-Shirt");
        SAUCE_LABS_FLEECE_JACKET_TITLE = CONFIG.getString("sauce_labs_fleece_jacket_title", "Sauce Labs Fleece Jacket");
        SAUCE_LABS_ONESIE_TITLE = CONFIG.getString("sauce_labs_onesie_title", "Sauce Labs Onesie");
        TEST_ALLTHETHINGS_TSHIRT_RED_TITLE = CONFIG.getString("test_allthethings_tshirt_red_title", "Test.allTheThings() T-Shirt (Red)");
        LIGHTHOUSE_COMMAND_PROPERTY = CONFIG.getString("lighthouse.command.property", "lighthouse.command");
        LIGHTHOUSE_COMMAND_ENV = CONFIG.getString("lighthouse.command.env", "LIGHTHOUSE_CMD");
        LIGHTHOUSE_REPORT_PATH = CONFIG.getString("lighthouse.report.path");
        APPLICATIONS_DOWNLOAD_FILEPATH = homeoffice.utilities.PathUtil.getDownloadsDir();
        APPLICATIONS_UPLOAD_FILEPATH = homeoffice.utilities.PathUtil.getUploadsDir();
        REPORTING_CSV_DOWNLOAD_FILEPATH = homeoffice.utilities.PathUtil.getReportingCsvDir();
        ACCESSIBILITY_REPORT_FILENAME = CONFIG.getString("accessibility_report_filename", "accessibilityResults.json");
        BUTTON_LABEL_ADD_TO_CART = CONFIG.getString("button_label_add_to_cart");
        BUTTON_LABEL_REMOVE = CONFIG.getString("button_label_remove");
        BUTTON_LABEL_CONTINUE_SHOPPING = CONFIG.getString("button_label_continue_shopping");
        BUTTON_LABEL_FINISH = CONFIG.getString("button_label_finish");
        BUTTON_LABEL_BACK_HOME = CONFIG.getString("button_label_back_home");
        BUTTON_LABEL_CHECKOUT = CONFIG.getString("button_label_checkout");
        BUTTON_LABEL_CONTINUE = CONFIG.getString("button_label_continue");
        BUTTON_LABEL_LOGOUT = CONFIG.getString("button_label_logout");
        BUTTON_LABEL_OPEN_MENU = CONFIG.getString("button_label_open_menu");
        BUTTON_LABEL_CLOSE_MENU = CONFIG.getString("button_label_close_menu");
        BUTTON_LABEL_RESET_APP_STATE = CONFIG.getString("button_label_reset_app_state");
        BUTTON_LABEL_ALL_ITEMS = CONFIG.getString("button_label_all_items");
        BUTTON_LABEL_ABOUT = CONFIG.getString("button_label_about");
        BUTTON_LABEL_LOGOUT_LINK = CONFIG.getString("button_label_logout_link");
        BUTTON_LABEL_LINKEDIN = CONFIG.getString("button_label_linkedin");
        BUTTON_LABEL_FACEBOOK = CONFIG.getString("button_label_facebook");
        BUTTON_LABEL_TWITTER = CONFIG.getString("button_label_twitter");
        BUTTON_LABEL_CONTINUE_TO_CHECKOUT = CONFIG.getString("button_label_continue_to_checkout");
        BUTTON_LABEL_BACK_TO_PRODUCTS = CONFIG.getString("button_label_back_to_products");
        BUTTON_LABEL_SHOPPING_CART = CONFIG.getString("button_label_shopping_cart");
        BUTTON_LABEL_REMOVE_ITEM = CONFIG.getString("button_label_remove_item");
        BUTTON_LABEL_ADD_ITEM = CONFIG.getString("button_label_add_item");
        BUTTON_LABEL_BACK = CONFIG.getString("button_label_back");
        SORT_OPTION_NAME_AZ = CONFIG.getString("sort_option_name_az", "Name (A to Z)");
        SORT_OPTION_NAME_ZA = CONFIG.getString("sort_option_name_za", "Name (Z to A)");
        SORT_OPTION_PRICE_LH = CONFIG.getString("sort_option_price_lh", "Price (low to high)");
        SORT_OPTION_PRICE_HL = CONFIG.getString("sort_option_price_hl", "Price (high to low)");
        LOCATOR_CART_ICON = CONFIG.getString("locator_cart_icon", "a.shopping_cart_link");
        LOCATOR_BURGER_MENU_BUTTON = CONFIG.getString("locator_burger_menu_button", "react-burger-menu-btn");
        EXCEL_LOGIN_FILE_NAME = CONFIG.getString("excel_login_file_name", "data/excelfiles/sauce_loginData.xlsx");
        EXCEL_LOGIN_SHEET_NAME = CONFIG.getString("excel_login_sheet_name", "Sheet1");
        CHECKOUT_OVERVIEW_PAGE_HEADING = CONFIG.getString("checkout_overview_page_heading", "Checkout: Overview");
    }

    private UserTestData() {
    }
}
