package homeoffice.enums;

public enum WaitStrategy {
    PAGE_LOAD,
    CLICKABLE,
    PRESENCE,
    VISIBLE,
    NONE,
    HANDLE_STALE_ELEMENT,
    URL_CONTAINS,
    TITLE_CONTAINS,
    INVISIBILITY,
    VISIBILITY_OF_ALL_ELEMENTS,
    ELEMENT_TO_BE_ENABLED,
    PRESENCE_OF_ALL_ELEMENTS_LOCATED,
    ELEMENT_TO_BE_INVISIBLE;

    // $FF: synthetic method
    private static WaitStrategy[] $values() {
        return new WaitStrategy[]{PAGE_LOAD, CLICKABLE, PRESENCE, VISIBLE, NONE, HANDLE_STALE_ELEMENT, URL_CONTAINS, TITLE_CONTAINS, INVISIBILITY, VISIBILITY_OF_ALL_ELEMENTS, ELEMENT_TO_BE_ENABLED, PRESENCE_OF_ALL_ELEMENTS_LOCATED, ELEMENT_TO_BE_INVISIBLE};
    }
}
